err_msg = 'text-negative text-weight-bold'
#exercise = 'text-left'
success_msg_classes = 'text-positive'
wrong_msg_classes = 'text-negative'
maincard_style = 'margin-top: 3%'
subcard_classes = 'w-full'