CREATE DATABASE 'rezepte';
USE 'rezepte';
CREATE TABLE 'mahlzeit' ('mahlzeit_id' INT PRIMARY KEY, 'mahlzeitname' VARCHAR(255), 'kalorien' INT, 'serviergroesse' VARCHAR(50));
INSERT INTO 'mahlzeit' VALUES ('1', 'Fruehstueck', '400', '1 Portion');
INSERT INTO 'mahlzeit' VALUES ('2', 'Mittagessen', '600', '1 Portion');
INSERT INTO 'mahlzeit' VALUES ('3', 'Abendessen', '700', '1 Portion');
INSERT INTO 'mahlzeit' VALUES ('4', 'Snack', '200', '1 Portion');
INSERT INTO 'mahlzeit' VALUES ('5', 'Dessert', '350', '1 Portion');
CREATE TABLE 'rezeptkategorie' ('rezeptkategorie_id' INT PRIMARY KEY, 'kategoriename' VARCHAR(255), 'beschreibung' TEXT, 'anzahlrezepte' INT);
INSERT INTO 'rezeptkategorie' VALUES ('1', 'Vegetarisch', 'Gerichte ohne Fleisch und Fisch.', '20');
INSERT INTO 'rezeptkategorie' VALUES ('2', 'Vegan', 'Gerichte ohne tierische Produkte.', '15');
INSERT INTO 'rezeptkategorie' VALUES ('3', 'Fleischgerichte', 'Gerichte mit Fleisch als Hauptzutat.', '30');
INSERT INTO 'rezeptkategorie' VALUES ('4', 'Fischgerichte', 'Gerichte mit Fisch oder Meeresfruechten.', '10');
INSERT INTO 'rezeptkategorie' VALUES ('5', 'Desserts', 'Suesse Nachspeisen und Gebaeck.', '25');
CREATE TABLE 'koch' ('koch_id' INT PRIMARY KEY, 'kochname' VARCHAR(255), 'erfahrung' INT, 'spezialgebiet' VARCHAR(255));
INSERT INTO 'koch' VALUES ('1', 'Julia Schneider', '10', 'Franzoesische Kueche');
INSERT INTO 'koch' VALUES ('2', 'Max Meier', '7', 'Asiatische Kueche');
INSERT INTO 'koch' VALUES ('3', 'Lena Schmidt', '5', 'Vegane Kueche');
INSERT INTO 'koch' VALUES ('4', 'Tom Mueller', '12', 'Italienische Kueche');
INSERT INTO 'koch' VALUES ('5', 'Anna Weber', '8', 'Backen');
CREATE TABLE 'rezept' ('rezept_id' INT PRIMARY KEY, 'rezeptname' VARCHAR(255), 'kochzeit' VARCHAR(50), 'schwierigkeitsgrad' VARCHAR(50), 'mahlzeit_id' INT, 'rezeptkategorie_id' INT, 'koch_id' INT);
INSERT INTO 'rezept' VALUES ('1', 'Spaghetti Carbonara', '25 Minuten', 'Mittel', '3', '3', '4');
INSERT INTO 'rezept' VALUES ('2', 'Linsen Dal', '40 Minuten', 'Leicht', '2', '2', '3');
INSERT INTO 'rezept' VALUES ('3', 'Haehnchen mit Gemuese', '45 Minuten', 'Mittel', '3', '3', '1');
INSERT INTO 'rezept' VALUES ('4', 'Quarkpfannkuchen', '20 Minuten', 'Leicht', '1', '5', '5');
INSERT INTO 'rezept' VALUES ('5', 'Griechischer Salat', '15 Minuten', 'Leicht', '2', '1', '1');
INSERT INTO 'rezept' VALUES ('6', 'Schokoladenmousse', '30 Minuten', 'Mittel', '5', '5', '5');
INSERT INTO 'rezept' VALUES ('7', 'Curry mit Kichererbsen', '35 Minuten', 'Mittel', '3', '2', '3');
INSERT INTO 'rezept' VALUES ('8', 'Rinderrouladen', '120 Minuten', 'Schwer', '3', '3', '1');
INSERT INTO 'rezept' VALUES ('9', 'Fischstaebchen mit Kartoffelsalat', '30 Minuten', 'Leicht', '2', '4', '2');
INSERT INTO 'rezept' VALUES ('10', 'Erdbeertorte', '60 Minuten', 'Mittel', '5', '5', '5');
INSERT INTO 'rezept' VALUES ('11', 'Vegetarische Lasagne', '50 Minuten', 'Mittel', '3', '1', '3');
INSERT INTO 'rezept' VALUES ('12', 'Sushi', '90 Minuten', 'Schwer', '3', '4', '2');
INSERT INTO 'rezept' VALUES ('13', 'Tomatensuppe', '25 Minuten', 'Leicht', '2', '1', '1');
INSERT INTO 'rezept' VALUES ('14', 'Bratwurst mit Sauerkraut', '30 Minuten', 'Leicht', '3', '3', '4');
INSERT INTO 'rezept' VALUES ('15', 'Haferflocken mit Fruechten', '10 Minuten', 'Leicht', '1', '2', '3');
CREATE TABLE 'zutat' ('zutat_id' INT PRIMARY KEY, 'zutatname' VARCHAR(255), 'menge' VARCHAR(50), 'masseinheit' VARCHAR(50));
INSERT INTO 'zutat' VALUES ('1', 'Spaghetti', '200', 'g');
INSERT INTO 'zutat' VALUES ('2', 'Eier', '2', 'Stueck');
INSERT INTO 'zutat' VALUES ('3', 'Speck', '100', 'g');
INSERT INTO 'zutat' VALUES ('4', 'Parmesan', '50', 'g');
INSERT INTO 'zutat' VALUES ('5', 'Rote Linsen', '250', 'g');
INSERT INTO 'zutat' VALUES ('6', 'Kokosmilch', '400', 'ml');
INSERT INTO 'zutat' VALUES ('7', 'Haehnchenbrust', '300', 'g');
INSERT INTO 'zutat' VALUES ('8', 'Brokkoli', '1', 'Kopf');
INSERT INTO 'zutat' VALUES ('9', 'Quark', '250', 'g');
INSERT INTO 'zutat' VALUES ('10', 'Mehl', '100', 'g');
INSERT INTO 'zutat' VALUES ('11', 'Salatgurke', '0.5', 'Stueck');
INSERT INTO 'zutat' VALUES ('12', 'Tomaten', '3', 'Stueck');
INSERT INTO 'zutat' VALUES ('13', 'Feta', '150', 'g');
INSERT INTO 'zutat' VALUES ('14', 'Zartbitterschokolade', '200', 'g');
INSERT INTO 'zutat' VALUES ('15', 'Sahne', '300', 'ml');
INSERT INTO 'zutat' VALUES ('16', 'Kichererbsen', '400', 'g');
INSERT INTO 'zutat' VALUES ('17', 'Currypaste', '2', 'EL');
INSERT INTO 'zutat' VALUES ('18', 'Rindfleisch', '500', 'g');
INSERT INTO 'zutat' VALUES ('19', 'Karotten', '2', 'Stueck');
INSERT INTO 'zutat' VALUES ('20', 'Fischstaebchen', '10', 'Stueck');
INSERT INTO 'zutat' VALUES ('21', 'Kartoffeln', '500', 'g');
INSERT INTO 'zutat' VALUES ('22', 'Erdbeeren', '500', 'g');
INSERT INTO 'zutat' VALUES ('23', 'Blaetterteig', '1', 'Rolle');
INSERT INTO 'zutat' VALUES ('24', 'Lasagneplatten', '200', 'g');
INSERT INTO 'zutat' VALUES ('25', 'Mozzarella', '200', 'g');
INSERT INTO 'zutat' VALUES ('26', 'Sushi Reis', '300', 'g');
INSERT INTO 'zutat' VALUES ('27', 'Nori-Blaetter', '5', 'Stueck');
INSERT INTO 'zutat' VALUES ('28', 'Lachs', '150', 'g');
INSERT INTO 'zutat' VALUES ('29', 'Passierte Tomaten', '500', 'g');
INSERT INTO 'zutat' VALUES ('30', 'Zwiebel', '1', 'Stueck');
INSERT INTO 'zutat' VALUES ('31', 'Bratwurst', '2', 'Stueck');
INSERT INTO 'zutat' VALUES ('32', 'Sauerkraut', '400', 'g');
INSERT INTO 'zutat' VALUES ('33', 'Haferflocken', '50', 'g');
INSERT INTO 'zutat' VALUES ('34', 'Beerenmix', '100', 'g');
CREATE TABLE 'rezept_zutat' ('rezept_zutat_id' INT PRIMARY KEY, 'rezept_id' INT, 'zutat_id' INT);
INSERT INTO 'rezept_zutat' VALUES ('1', '1', '1');
INSERT INTO 'rezept_zutat' VALUES ('2', '1', '2');
INSERT INTO 'rezept_zutat' VALUES ('3', '1', '3');
INSERT INTO 'rezept_zutat' VALUES ('4', '1', '4');
INSERT INTO 'rezept_zutat' VALUES ('5', '2', '5');
INSERT INTO 'rezept_zutat' VALUES ('6', '2', '6');
INSERT INTO 'rezept_zutat' VALUES ('7', '3', '7');
INSERT INTO 'rezept_zutat' VALUES ('8', '3', '8');
INSERT INTO 'rezept_zutat' VALUES ('9', '4', '9');
INSERT INTO 'rezept_zutat' VALUES ('10', '4', '10');
INSERT INTO 'rezept_zutat' VALUES ('11', '5', '11');
INSERT INTO 'rezept_zutat' VALUES ('12', '5', '12');
INSERT INTO 'rezept_zutat' VALUES ('13', '5', '13');
INSERT INTO 'rezept_zutat' VALUES ('14', '6', '14');
INSERT INTO 'rezept_zutat' VALUES ('15', '6', '15');
INSERT INTO 'rezept_zutat' VALUES ('16', '7', '16');
INSERT INTO 'rezept_zutat' VALUES ('17', '7', '17');
INSERT INTO 'rezept_zutat' VALUES ('18', '8', '18');
INSERT INTO 'rezept_zutat' VALUES ('19', '8', '19');
INSERT INTO 'rezept_zutat' VALUES ('20', '9', '20');
INSERT INTO 'rezept_zutat' VALUES ('21', '9', '21');
INSERT INTO 'rezept_zutat' VALUES ('22', '10', '22');
INSERT INTO 'rezept_zutat' VALUES ('23', '10', '23');
INSERT INTO 'rezept_zutat' VALUES ('24', '11', '12');
INSERT INTO 'rezept_zutat' VALUES ('25', '11', '24');
INSERT INTO 'rezept_zutat' VALUES ('26', '11', '25');
INSERT INTO 'rezept_zutat' VALUES ('27', '12', '26');
INSERT INTO 'rezept_zutat' VALUES ('28', '12', '27');
INSERT INTO 'rezept_zutat' VALUES ('29', '12', '28');
INSERT INTO 'rezept_zutat' VALUES ('30', '13', '12');
INSERT INTO 'rezept_zutat' VALUES ('31', '13', '29');
INSERT INTO 'rezept_zutat' VALUES ('32', '13', '30');
INSERT INTO 'rezept_zutat' VALUES ('33', '14', '31');
INSERT INTO 'rezept_zutat' VALUES ('34', '14', '32');
INSERT INTO 'rezept_zutat' VALUES ('35', '15', '33');
INSERT INTO 'rezept_zutat' VALUES ('36', '15', '34');
CREATE TABLE 'kochkurs' ('kurs_id' INT PRIMARY KEY, 'kursname' VARCHAR(255), 'datum' DATE, 'ort' VARCHAR(255));
INSERT INTO 'kochkurs' VALUES ('1', 'Italienische Pasta', '2024-06-10', 'Kochstudio Frankfurt');
INSERT INTO 'kochkurs' VALUES ('2', 'Vegan Backen', '2024-07-05', 'Kochschule Berlin');
INSERT INTO 'kochkurs' VALUES ('3', 'Asiatische Streetfood', '2024-08-20', 'Kochstudio Muenchen');
INSERT INTO 'kochkurs' VALUES ('4', 'Franzoesische Desserts', '2024-09-15', 'Kochschule Hamburg');
INSERT INTO 'kochkurs' VALUES ('5', 'Deutsche Hausmannskost', '2024-10-01', 'Kochstudio Koeln');
CREATE TABLE 'koch_kochkurs' ('koch_kurs_id' INT PRIMARY KEY, 'koch_id' INT, 'kurs_id' INT);
INSERT INTO 'koch_kochkurs' VALUES ('1', '4', '1');
INSERT INTO 'koch_kochkurs' VALUES ('2', '3', '2');
INSERT INTO 'koch_kochkurs' VALUES ('3', '2', '3');
INSERT INTO 'koch_kochkurs' VALUES ('4', '1', '4');
INSERT INTO 'koch_kochkurs' VALUES ('5', '5', '4');
INSERT INTO 'koch_kochkurs' VALUES ('6', '1', '1');
INSERT INTO 'koch_kochkurs' VALUES ('7', '4', '5');
