CREATE DATABASE 'berufsberatung';
USE 'berufsberatung';
CREATE TABLE 'berufsfelder' ('berufsfeld_id' INT PRIMARY KEY, 'feldname' VARCHAR(255), 'beschreibung' TEXT, 'anzahl_berufe' INT);
INSERT INTO 'berufsfelder' VALUES ('1', 'IT & Softwareentwicklung', 'Umfasst alle Taetigkeiten im Bereich Informationstechnologie und Softwareentwicklung.', '15');
INSERT INTO 'berufsfelder' VALUES ('2', 'Gesundheit & Medizin', 'Beinhaltet Berufe im Gesundheitswesen und medizinischen Bereich.', '20');
INSERT INTO 'berufsfelder' VALUES ('3', 'Handwerk & Technik', 'Berufe im handwerklichen und technischen Sektor.', '18');
INSERT INTO 'berufsfelder' VALUES ('4', 'Wirtschaft & Finanzen', 'Fokus auf kaufmaennische Berufe, Finanzen und Management.', '12');
INSERT INTO 'berufsfelder' VALUES ('5', 'Kreativ & Medien', 'Berufe in Kunst, Design, Medien und Kommunikation.', '10');
INSERT INTO 'berufsfelder' VALUES ('6', 'Bildung & Soziales', 'Berufe in Bildung, Erziehung und sozialer Arbeit.', '10');
CREATE TABLE 'berufe' ('beruf_id' INT PRIMARY KEY, 'berufsbezeichnung' VARCHAR(255), 'beschreibung' TEXT, 'durchschnittsgehalt' DEC(10,2), 'berufsfeld_id' INT);
INSERT INTO 'berufe' VALUES ('1', 'Softwareentwickler', 'Entwickelt und pflegt Softwareanwendungen.', '60000.0', '1');
INSERT INTO 'berufe' VALUES ('2', 'Krankenpfleger', 'Pflegt und betreut Patienten in medizinischen Einrichtungen.', '45000.0', '2');
INSERT INTO 'berufe' VALUES ('3', 'Elektriker', 'Installiert und wartet elektrische Anlagen.', '40000.0', '3');
INSERT INTO 'berufe' VALUES ('4', 'Buchhalter', 'Verwaltet Finanzunterlagen und erstellt Bilanzen.', '50000.0', '4');
INSERT INTO 'berufe' VALUES ('5', 'Grafikdesigner', 'Erstellt visuelle Konzepte und Layouts.', '42000.0', '5');
INSERT INTO 'berufe' VALUES ('6', 'Lehrer', 'Unterrichtet Schueler in verschiedenen Faechern.', '55000.0', '6');
INSERT INTO 'berufe' VALUES ('7', 'Datenbankadministrator', 'Verwaltet und optimiert Datenbanksysteme.', '65000.0', '1');
INSERT INTO 'berufe' VALUES ('8', 'Arzt', 'Diagnostiziert Krankheiten und behandelt Patienten.', '90000.0', '2');
INSERT INTO 'berufe' VALUES ('9', 'Mechatroniker', 'Kombiniert Mechanik, Elektronik und Informatik.', '48000.0', '3');
INSERT INTO 'berufe' VALUES ('10', 'Investmentbanker', 'Beratung bei Finanztransaktionen und Kapitalmaerkten.', '120000.0', '4');
INSERT INTO 'berufe' VALUES ('11', 'Fotograf', 'Erstellt professionelle Fotografien fuer verschiedene Zwecke.', '38000.0', '5');
INSERT INTO 'berufe' VALUES ('12', 'Sozialarbeiter', 'Unterstuetzt Menschen in sozialen Notlagen.', '44000.0', '6');
INSERT INTO 'berufe' VALUES ('13', 'Systemadministrator', 'Betreut und wartet IT-Systeme und Netzwerke.', '58000.0', '1');
INSERT INTO 'berufe' VALUES ('14', 'Physiotherapeut', 'Behandelt koerperliche Beschwerden durch Bewegungstherapie.', '39000.0', '2');
INSERT INTO 'berufe' VALUES ('15', 'Bauingenieur', 'Plant und ueberwacht Bauprojekte.', '62000.0', '3');
INSERT INTO 'berufe' VALUES ('16', 'Marketing Manager', 'Entwickelt und implementiert Marketingstrategien.', '57000.0', '4');
INSERT INTO 'berufe' VALUES ('17', 'Webdesigner', 'Gestaltet und entwickelt Webseiten.', '43000.0', '5');
INSERT INTO 'berufe' VALUES ('18', 'Erzieher', 'Betreut und foerdert Kinder in paedagogischen Einrichtungen.', '37000.0', '6');
INSERT INTO 'berufe' VALUES ('19', 'Netzwerktechniker', 'Konfiguriert und wartet Computernetzwerke.', '54000.0', '1');
INSERT INTO 'berufe' VALUES ('20', 'Apotheker', 'Beraet zu Medikamenten und deren Anwendung.', '68000.0', '2');
INSERT INTO 'berufe' VALUES ('21', 'Heizungsinstallateur', 'Installiert und wartet Heizungs- und Sanitaeranlagen.', '41000.0', '3');
INSERT INTO 'berufe' VALUES ('22', 'Controller', 'Ueberwacht und steuert Unternehmensfinanzen.', '63000.0', '4');
INSERT INTO 'berufe' VALUES ('23', 'Journalist', 'Recherchiert und verfasst Nachrichten und Artikel.', '49000.0', '5');
INSERT INTO 'berufe' VALUES ('24', 'Psychologe', 'Untersucht und behandelt psychische Stoerungen.', '56000.0', '6');
INSERT INTO 'berufe' VALUES ('25', 'Cybersecurity-Spezialist', 'Schuetzt Computersysteme vor Angriffen.', '70000.0', '1');
INSERT INTO 'berufe' VALUES ('26', 'Zahnarzt', 'Untersucht, diagnostiziert und behandelt Erkrankungen im Mundbereich.', '85000.0', '2');
INSERT INTO 'berufe' VALUES ('27', 'Maschinenbauingenieur', 'Entwickelt, konstruiert und fertigt Maschinen und Anlagen.', '67000.0', '3');
INSERT INTO 'berufe' VALUES ('28', 'Steuerberater', 'Beraet Mandanten in steuerlichen Angelegenheiten.', '75000.0', '4');
INSERT INTO 'berufe' VALUES ('29', 'Filmproduzent', 'Plant, organisiert und ueberwacht die Produktion von Filmen.', '60000.0', '5');
INSERT INTO 'berufe' VALUES ('30', 'Sonderschullehrer', 'Unterrichtet und foerdert Schueler mit besonderen Beduerfnissen.', '52000.0', '6');
CREATE TABLE 'praktika' ('praktikum_id' INT PRIMARY KEY, 'praktikumsbezeichnung' VARCHAR(255), 'dauer_wochen' INT, 'verguetung' DEC(10,2));
INSERT INTO 'praktika' VALUES ('1', 'Softwareentwicklung Praktikum', '12', '800.0');
INSERT INTO 'praktika' VALUES ('2', 'Pflegepraktikum', '8', '400.0');
INSERT INTO 'praktika' VALUES ('3', 'Elektrotechnik Praktikum', '10', '600.0');
INSERT INTO 'praktika' VALUES ('4', 'Finanzmanagement Praktikum', '16', '1000.0');
INSERT INTO 'praktika' VALUES ('5', 'Mediendesign Praktikum', '12', '700.0');
INSERT INTO 'praktika' VALUES ('6', 'Lehramtspraktikum', '4', '200.0');
INSERT INTO 'praktika' VALUES ('7', 'IT-Support Praktikum', '8', '500.0');
INSERT INTO 'praktika' VALUES ('8', 'Assistenzarzt Praktikum', '24', '1200.0');
INSERT INTO 'praktika' VALUES ('9', 'Produktionstechnik Praktikum', '12', '750.0');
INSERT INTO 'praktika' VALUES ('10', 'Marketing Praktikum', '10', '650.0');
INSERT INTO 'praktika' VALUES ('11', 'Journalismus Praktikum', '8', '550.0');
INSERT INTO 'praktika' VALUES ('12', 'Sozialarbeit Praktikum', '12', '600.0');
CREATE TABLE 'beruf_praktikum' ('beruf_id' INT, 'praktikum_id' INT);
INSERT INTO 'beruf_praktikum' VALUES ('1', '1');
INSERT INTO 'beruf_praktikum' VALUES ('7', '1');
INSERT INTO 'beruf_praktikum' VALUES ('13', '7');
INSERT INTO 'beruf_praktikum' VALUES ('19', '7');
INSERT INTO 'beruf_praktikum' VALUES ('2', '2');
INSERT INTO 'beruf_praktikum' VALUES ('14', '2');
INSERT INTO 'beruf_praktikum' VALUES ('8', '8');
INSERT INTO 'beruf_praktikum' VALUES ('20', '8');
INSERT INTO 'beruf_praktikum' VALUES ('3', '3');
INSERT INTO 'beruf_praktikum' VALUES ('9', '9');
INSERT INTO 'beruf_praktikum' VALUES ('15', '3');
INSERT INTO 'beruf_praktikum' VALUES ('21', '3');
INSERT INTO 'beruf_praktikum' VALUES ('4', '4');
INSERT INTO 'beruf_praktikum' VALUES ('10', '4');
INSERT INTO 'beruf_praktikum' VALUES ('16', '10');
INSERT INTO 'beruf_praktikum' VALUES ('22', '10');
INSERT INTO 'beruf_praktikum' VALUES ('5', '5');
INSERT INTO 'beruf_praktikum' VALUES ('11', '5');
INSERT INTO 'beruf_praktikum' VALUES ('17', '5');
INSERT INTO 'beruf_praktikum' VALUES ('23', '11');
INSERT INTO 'beruf_praktikum' VALUES ('6', '6');
INSERT INTO 'beruf_praktikum' VALUES ('12', '12');
INSERT INTO 'beruf_praktikum' VALUES ('18', '6');
INSERT INTO 'beruf_praktikum' VALUES ('24', '12');
CREATE TABLE 'schulleiter' ('schulleiter_id' INT PRIMARY KEY, 'name' VARCHAR(255), 'geburtsdatum' DATE);
INSERT INTO 'schulleiter' VALUES ('1', 'Dr. Anna Meier', '1970-05-15');
INSERT INTO 'schulleiter' VALUES ('2', 'Prof. Klaus Schmidt', '1965-11-22');
INSERT INTO 'schulleiter' VALUES ('3', 'Sabine Mueller', '1978-03-01');
INSERT INTO 'schulleiter' VALUES ('4', 'Thomas Klein', '1972-09-30');
INSERT INTO 'schulleiter' VALUES ('5', 'Maria Weber', '1980-01-10');
CREATE TABLE 'schulen' ('schul_id' INT PRIMARY KEY, 'schulname' VARCHAR(255), 'ort' VARCHAR(255), 'schultyp' VARCHAR(255), 'schulleiter_id' INT);
INSERT INTO 'schulen' VALUES ('1', 'Goethe-Gymnasium', 'Frankfurt am Main', 'Gymnasium', '1');
INSERT INTO 'schulen' VALUES ('2', 'Berufliche Schulen Offenbach', 'Offenbach am Main', 'Berufsschule', '2');
INSERT INTO 'schulen' VALUES ('3', 'Adolf-Reichwein-Schule', 'Wiesbaden', 'Gesamtschule', '3');
INSERT INTO 'schulen' VALUES ('4', 'Grundschule am Wald', 'Bad Homburg', 'Grundschule', '4');
INSERT INTO 'schulen' VALUES ('5', 'Technikerschule Darmstadt', 'Darmstadt', 'Fachschule', '5');
