CREATE DATABASE 'musikarchiv';
USE 'musikarchiv';
CREATE TABLE 'kuenstler' ('kuenstler_id' INT PRIMARY KEY, 'name' VARCHAR(255), 'geburtsdatum' DATE, 'instrument' VARCHAR(255));
INSERT INTO 'kuenstler' VALUES ('1', 'Freddie Mercury', '1946-09-05', 'Gesang, Klavier');
INSERT INTO 'kuenstler' VALUES ('2', 'Brian May', '1947-07-19', 'Gitarre');
INSERT INTO 'kuenstler' VALUES ('3', 'John Deacon', '1951-08-19', 'Bass');
INSERT INTO 'kuenstler' VALUES ('4', 'Roger Taylor', '1949-07-26', 'Schlagzeug');
INSERT INTO 'kuenstler' VALUES ('5', 'Adele Adkins', '1988-05-05', 'Gesang');
INSERT INTO 'kuenstler' VALUES ('6', 'Ed Sheeran', '1991-02-17', 'Gesang, Gitarre');
INSERT INTO 'kuenstler' VALUES ('7', 'Beyoncé Knowles', '1981-09-04', 'Gesang');
INSERT INTO 'kuenstler' VALUES ('8', 'Chris Martin', '1977-03-02', 'Gesang, Klavier');
INSERT INTO 'kuenstler' VALUES ('9', 'Jon Buckland', '1977-09-11', 'Gitarre');
INSERT INTO 'kuenstler' VALUES ('10', 'Guy Berryman', '1978-04-12', 'Bass');
INSERT INTO 'kuenstler' VALUES ('11', 'Will Champion', '1978-07-31', 'Schlagzeug');
INSERT INTO 'kuenstler' VALUES ('12', 'Taylor Swift', '1989-12-13', 'Gesang, Gitarre');
INSERT INTO 'kuenstler' VALUES ('13', 'Dua Lipa', '1995-08-22', 'Gesang');
INSERT INTO 'kuenstler' VALUES ('14', 'The Weeknd', '1990-02-16', 'Gesang');
INSERT INTO 'kuenstler' VALUES ('15', 'Billie Eilish', '2001-12-18', 'Gesang');
CREATE TABLE 'musikgruppe' ('musikgruppe_id' INT PRIMARY KEY, 'gruppenname' VARCHAR(255), 'gruendungsjahr' YEAR, 'anzahl_mitglieder' INT);
INSERT INTO 'musikgruppe' VALUES ('1', 'Queen', '1970', '4');
INSERT INTO 'musikgruppe' VALUES ('2', 'Coldplay', '1997', '4');
INSERT INTO 'musikgruppe' VALUES ('3', 'Imagine Dragons', '2008', '4');
INSERT INTO 'musikgruppe' VALUES ('4', 'OneRepublic', '2002', '5');
CREATE TABLE 'musikgruppe_kuenstler' ('musikgruppe_id' INT, 'kuenstler_id' INT);
INSERT INTO 'musikgruppe_kuenstler' VALUES ('1', '1');
INSERT INTO 'musikgruppe_kuenstler' VALUES ('1', '2');
INSERT INTO 'musikgruppe_kuenstler' VALUES ('1', '3');
INSERT INTO 'musikgruppe_kuenstler' VALUES ('1', '4');
INSERT INTO 'musikgruppe_kuenstler' VALUES ('2', '8');
INSERT INTO 'musikgruppe_kuenstler' VALUES ('2', '9');
INSERT INTO 'musikgruppe_kuenstler' VALUES ('2', '10');
INSERT INTO 'musikgruppe_kuenstler' VALUES ('2', '11');
CREATE TABLE 'alben' ('album_id' INT PRIMARY KEY, 'albumtitel' VARCHAR(255), 'veroeffentlichungsjahr' YEAR, 'musikgruppe_id' INT);
INSERT INTO 'alben' VALUES ('1', 'A Night at the Opera', '1975', '1');
INSERT INTO 'alben' VALUES ('2', 'The Game', '1980', '1');
INSERT INTO 'alben' VALUES ('3', '21', '2011', 'None');
INSERT INTO 'alben' VALUES ('4', '÷', '2017', 'None');
INSERT INTO 'alben' VALUES ('5', 'Lemonade', '2016', 'None');
INSERT INTO 'alben' VALUES ('6', 'A Head Full of Dreams', '2015', '2');
INSERT INTO 'alben' VALUES ('7', 'X&Y', '2005', '2');
INSERT INTO 'alben' VALUES ('8', 'Fearless', '2008', 'None');
INSERT INTO 'alben' VALUES ('9', 'Future Nostalgia', '2020', 'None');
INSERT INTO 'alben' VALUES ('10', 'After Hours', '2020', 'None');
INSERT INTO 'alben' VALUES ('11', 'Happier Than Ever', '2021', 'None');
INSERT INTO 'alben' VALUES ('12', 'Night Visions', '2012', '3');
CREATE TABLE 'genres' ('genre_id' INT PRIMARY KEY, 'genre_name' VARCHAR(255));
INSERT INTO 'genres' VALUES ('1', 'Rock');
INSERT INTO 'genres' VALUES ('2', 'Pop');
INSERT INTO 'genres' VALUES ('3', 'Soul');
INSERT INTO 'genres' VALUES ('4', 'R&B');
INSERT INTO 'genres' VALUES ('5', 'Alternative Rock');
INSERT INTO 'genres' VALUES ('6', 'Electronic');
INSERT INTO 'genres' VALUES ('7', 'Indie Pop');
CREATE TABLE 'lieder' ('lied_id' INT PRIMARY KEY, 'titel' VARCHAR(255), 'dauer' TIME, 'erscheinungsjahr' YEAR, 'album_id' INT, 'genre_id' INT);
INSERT INTO 'lieder' VALUES ('1', 'Bohemian Rhapsody', '00:05:55', '1975', '1', '1');
INSERT INTO 'lieder' VALUES ('2', 'Another One Bites the Dust', '00:03:36', '1980', '2', '1');
INSERT INTO 'lieder' VALUES ('3', 'Someone Like You', '00:04:47', '2011', '3', '2');
INSERT INTO 'lieder' VALUES ('4', 'Shape of You', '00:03:53', '2017', '4', '2');
INSERT INTO 'lieder' VALUES ('5', 'Formation', '00:03:26', '2016', '5', '4');
INSERT INTO 'lieder' VALUES ('6', 'Hymn for the Weekend', '00:04:18', '2015', '6', '2');
INSERT INTO 'lieder' VALUES ('7', 'Fix You', '00:04:55', '2005', '7', '5');
INSERT INTO 'lieder' VALUES ('8', 'Love Story', '00:03:55', '2008', '8', '2');
INSERT INTO 'lieder' VALUES ('9', 'Dont Start Now', '00:03:03', '2019', '9', '2');
INSERT INTO 'lieder' VALUES ('10', 'Blinding Lights', '00:03:20', '2019', '10', '6');
INSERT INTO 'lieder' VALUES ('11', 'Bad Guy', '00:03:14', '2019', '11', '7');
INSERT INTO 'lieder' VALUES ('12', 'Radioactive', '00:03:07', '2012', '12', '5');
INSERT INTO 'lieder' VALUES ('13', 'Killer Queen', '00:02:59', '1974', '1', '1');
INSERT INTO 'lieder' VALUES ('14', 'Crazy Little Thing Called Love', '00:02:55', '1979', '2', '1');
INSERT INTO 'lieder' VALUES ('15', 'Rolling in the Deep', '00:03:48', '2010', '3', '2');
INSERT INTO 'lieder' VALUES ('16', 'Thinking Out Loud', '00:04:41', '2014', '4', '2');
INSERT INTO 'lieder' VALUES ('17', 'Halo', '00:04:21', '2008', '5', '4');
INSERT INTO 'lieder' VALUES ('18', 'Viva La Vida', '00:04:02', '2008', '6', '5');
INSERT INTO 'lieder' VALUES ('19', 'The Scientist', '00:05:09', '2002', '7', '5');
INSERT INTO 'lieder' VALUES ('20', 'You Belong With Me', '00:03:57', '2008', '8', '2');
INSERT INTO 'lieder' VALUES ('21', 'Physical', '00:03:13', '2020', '9', '2');
INSERT INTO 'lieder' VALUES ('22', 'Heartless', '00:03:21', '2019', '10', '6');
INSERT INTO 'lieder' VALUES ('23', 'NDA', '00:03:12', '2021', '11', '7');
INSERT INTO 'lieder' VALUES ('24', 'Demons', '00:02:57', '2012', '12', '5');
CREATE TABLE 'lieder_kuenstler' ('lied_id' INT, 'kuenstler_id' INT);
INSERT INTO 'lieder_kuenstler' VALUES ('1', '1');
INSERT INTO 'lieder_kuenstler' VALUES ('1', '2');
INSERT INTO 'lieder_kuenstler' VALUES ('1', '3');
INSERT INTO 'lieder_kuenstler' VALUES ('1', '4');
INSERT INTO 'lieder_kuenstler' VALUES ('2', '1');
INSERT INTO 'lieder_kuenstler' VALUES ('2', '2');
INSERT INTO 'lieder_kuenstler' VALUES ('2', '3');
INSERT INTO 'lieder_kuenstler' VALUES ('2', '4');
INSERT INTO 'lieder_kuenstler' VALUES ('3', '5');
INSERT INTO 'lieder_kuenstler' VALUES ('4', '6');
INSERT INTO 'lieder_kuenstler' VALUES ('5', '7');
INSERT INTO 'lieder_kuenstler' VALUES ('6', '8');
INSERT INTO 'lieder_kuenstler' VALUES ('6', '9');
INSERT INTO 'lieder_kuenstler' VALUES ('6', '10');
INSERT INTO 'lieder_kuenstler' VALUES ('6', '11');
INSERT INTO 'lieder_kuenstler' VALUES ('7', '8');
INSERT INTO 'lieder_kuenstler' VALUES ('7', '9');
INSERT INTO 'lieder_kuenstler' VALUES ('7', '10');
INSERT INTO 'lieder_kuenstler' VALUES ('7', '11');
INSERT INTO 'lieder_kuenstler' VALUES ('8', '12');
INSERT INTO 'lieder_kuenstler' VALUES ('9', '13');
INSERT INTO 'lieder_kuenstler' VALUES ('10', '14');
INSERT INTO 'lieder_kuenstler' VALUES ('11', '15');
INSERT INTO 'lieder_kuenstler' VALUES ('12', '8');
INSERT INTO 'lieder_kuenstler' VALUES ('12', '9');
INSERT INTO 'lieder_kuenstler' VALUES ('12', '10');
INSERT INTO 'lieder_kuenstler' VALUES ('12', '11');
INSERT INTO 'lieder_kuenstler' VALUES ('13', '1');
INSERT INTO 'lieder_kuenstler' VALUES ('13', '2');
INSERT INTO 'lieder_kuenstler' VALUES ('13', '3');
INSERT INTO 'lieder_kuenstler' VALUES ('13', '4');
INSERT INTO 'lieder_kuenstler' VALUES ('14', '1');
INSERT INTO 'lieder_kuenstler' VALUES ('14', '2');
INSERT INTO 'lieder_kuenstler' VALUES ('14', '3');
INSERT INTO 'lieder_kuenstler' VALUES ('14', '4');
INSERT INTO 'lieder_kuenstler' VALUES ('15', '5');
INSERT INTO 'lieder_kuenstler' VALUES ('16', '6');
INSERT INTO 'lieder_kuenstler' VALUES ('17', '7');
INSERT INTO 'lieder_kuenstler' VALUES ('18', '8');
INSERT INTO 'lieder_kuenstler' VALUES ('18', '9');
INSERT INTO 'lieder_kuenstler' VALUES ('18', '10');
INSERT INTO 'lieder_kuenstler' VALUES ('18', '11');
INSERT INTO 'lieder_kuenstler' VALUES ('19', '8');
INSERT INTO 'lieder_kuenstler' VALUES ('19', '9');
INSERT INTO 'lieder_kuenstler' VALUES ('19', '10');
INSERT INTO 'lieder_kuenstler' VALUES ('19', '11');
INSERT INTO 'lieder_kuenstler' VALUES ('20', '12');
INSERT INTO 'lieder_kuenstler' VALUES ('21', '13');
INSERT INTO 'lieder_kuenstler' VALUES ('22', '14');
INSERT INTO 'lieder_kuenstler' VALUES ('23', '15');
INSERT INTO 'lieder_kuenstler' VALUES ('24', '8');
INSERT INTO 'lieder_kuenstler' VALUES ('24', '9');
INSERT INTO 'lieder_kuenstler' VALUES ('24', '10');
INSERT INTO 'lieder_kuenstler' VALUES ('24', '11');
