CREATE DATABASE 'geschichte';
USE 'geschichte';
CREATE TABLE 'ereignisse' ('ereignis_id' INTEGER PRIMARY KEY, 'beschreibung' TEXT, 'jahr' INTEGER, 'ort' TEXT, 'epoche_id' INTEGER, 'kulturkreis_id' INTEGER);
INSERT INTO 'ereignisse' VALUES ('1', 'Bau der Pyramiden von Gizeh', '-2580', 'Gizeh, Aegypten', '1', '1');
INSERT INTO 'ereignisse' VALUES ('2', 'Schlacht von Marathon', '-490', 'Marathon, Griechenland', '2', '2');
INSERT INTO 'ereignisse' VALUES ('3', 'Fall des Westroemischen Reiches', '476', 'Rom, Italien', '3', '2');
INSERT INTO 'ereignisse' VALUES ('4', 'Schlacht bei Hastings', '1066', 'Hastings, England', '4', '3');
INSERT INTO 'ereignisse' VALUES ('5', 'Entdeckung Amerikas durch Kolumbus', '1492', 'Atlantischer Ozean', '5', '3');
INSERT INTO 'ereignisse' VALUES ('6', 'Beginn der Reformation', '1517', 'Wittenberg, Deutschland', '5', '3');
INSERT INTO 'ereignisse' VALUES ('7', 'Franzoesische Revolution', '1789', 'Paris, Frankreich', '6', '3');
INSERT INTO 'ereignisse' VALUES ('8', 'Erster Weltkrieg', '1914', 'Weltweit', '7', '3');
INSERT INTO 'ereignisse' VALUES ('9', 'Zweiter Weltkrieg', '1939', 'Weltweit', '7', '3');
INSERT INTO 'ereignisse' VALUES ('10', 'Mauerfall in Berlin', '1989', 'Berlin, Deutschland', '8', '3');
INSERT INTO 'ereignisse' VALUES ('11', 'Gruendung des Osmanischen Reiches', '1299', 'Soeğuet, Anatolien', '4', '4');
INSERT INTO 'ereignisse' VALUES ('12', 'Erfindung der Schrift (Keilschrift)', '-3400', 'Mesopotamien', '1', '5');
INSERT INTO 'ereignisse' VALUES ('13', 'Etablierung des Roemischen Reiches', '-27', 'Rom, Italien', '2', '2');
INSERT INTO 'ereignisse' VALUES ('14', 'Beginn des Zeitalters der Aufklaerung', '1700', 'Europa', '6', '3');
INSERT INTO 'ereignisse' VALUES ('15', 'Bau der Chinesischen Mauer', '-220', 'China', '2', '6');
INSERT INTO 'ereignisse' VALUES ('16', 'Schlacht von Waterloo', '1815', 'Waterloo, Belgien', '6', '3');
INSERT INTO 'ereignisse' VALUES ('17', 'Industrielle Revolution', '1760', 'Grossbritannien', '6', '3');
INSERT INTO 'ereignisse' VALUES ('18', 'Apollo 11 Mondlandung', '1969', 'Mond', '8', '7');
INSERT INTO 'ereignisse' VALUES ('19', 'Gruendung der Vereinten Nationen', '1945', 'San Francisco, USA', '8', '7');
INSERT INTO 'ereignisse' VALUES ('20', 'Pest in Europa (Schwarzer Tod)', '1347', 'Europa', '4', '3');
CREATE TABLE 'persoenlichkeiten' ('persoenlichkeit_id' INTEGER PRIMARY KEY, 'name' TEXT, 'geburtsjahr' INTEGER, 'beruf' TEXT);
INSERT INTO 'persoenlichkeiten' VALUES ('1', 'Kleopatra VII.', '-69', 'Pharaonin');
INSERT INTO 'persoenlichkeiten' VALUES ('2', 'Alexander der Grosse', '-356', 'Koenig, Feldherr');
INSERT INTO 'persoenlichkeiten' VALUES ('3', 'Julius Caesar', '-100', 'Staatsmann, Feldherr');
INSERT INTO 'persoenlichkeiten' VALUES ('4', 'Karl der Grosse', '747', 'Kaiser');
INSERT INTO 'persoenlichkeiten' VALUES ('5', 'Jeanne dArc', '1412', 'Heilige, Militaerfuehrerin');
INSERT INTO 'persoenlichkeiten' VALUES ('6', 'Leonardo da Vinci', '1452', 'Kuenstler, Erfinder');
INSERT INTO 'persoenlichkeiten' VALUES ('7', 'Martin Luther', '1483', 'Theologe, Reformator');
INSERT INTO 'persoenlichkeiten' VALUES ('8', 'Napoleon Bonaparte', '1769', 'Kaiser, Feldherr');
INSERT INTO 'persoenlichkeiten' VALUES ('9', 'Marie Curie', '1867', 'Physikerin, Chemikerin');
INSERT INTO 'persoenlichkeiten' VALUES ('10', 'Albert Einstein', '1879', 'Physiker');
INSERT INTO 'persoenlichkeiten' VALUES ('11', 'Winston Churchill', '1874', 'Premierminister');
INSERT INTO 'persoenlichkeiten' VALUES ('12', 'George Washington', '1732', 'Praesident');
INSERT INTO 'persoenlichkeiten' VALUES ('13', 'Dschingis Khan', '1162', 'Khan, Feldherr');
INSERT INTO 'persoenlichkeiten' VALUES ('14', 'Sokrates', '-470', 'Philosoph');
INSERT INTO 'persoenlichkeiten' VALUES ('15', 'Isaac Newton', '1642', 'Physiker, Mathematiker');
INSERT INTO 'persoenlichkeiten' VALUES ('16', 'Galileo Galilei', '1564', 'Astronom, Physiker');
INSERT INTO 'persoenlichkeiten' VALUES ('17', 'William Shakespeare', '1564', 'Dramatiker, Dichter');
INSERT INTO 'persoenlichkeiten' VALUES ('18', 'Nelson Mandela', '1918', 'Praesident, Aktivist');
INSERT INTO 'persoenlichkeiten' VALUES ('19', 'Konfuzius', '-551', 'Philosoph');
INSERT INTO 'persoenlichkeiten' VALUES ('20', 'Hippokrates', '-460', 'Arzt');
CREATE TABLE 'epochen' ('epoche_id' INTEGER PRIMARY KEY, 'name' TEXT, 'startjahr' INTEGER, 'endjahr' INTEGER);
INSERT INTO 'epochen' VALUES ('1', 'Antike (Fruehzeit)', '-3500', '-500');
INSERT INTO 'epochen' VALUES ('2', 'Antike (Klassik)', '-500', '500');
INSERT INTO 'epochen' VALUES ('3', 'Fruehmittelalter', '500', '1000');
INSERT INTO 'epochen' VALUES ('4', 'Hochmittelalter', '1000', '1300');
INSERT INTO 'epochen' VALUES ('5', 'Spaetmittelalter/Fruehe Neuzeit', '1300', '1600');
INSERT INTO 'epochen' VALUES ('6', 'Neuzeit (bis Industrielle Revolution)', '1600', '1850');
INSERT INTO 'epochen' VALUES ('7', 'Moderne', '1850', '1945');
INSERT INTO 'epochen' VALUES ('8', 'Zeitgeschichte', '1945', '2024');
CREATE TABLE 'kulturkreis' ('kulturkreis_id' INTEGER PRIMARY KEY, 'name' TEXT, 'region' TEXT, 'hauptsprache' TEXT);
INSERT INTO 'kulturkreis' VALUES ('1', 'Aegyptische Hochkultur', 'Nordafrika', 'Aegyptisch');
INSERT INTO 'kulturkreis' VALUES ('2', 'Griechisch-Roemische Antike', 'Mittelmeerraum', 'Griechisch, Latein');
INSERT INTO 'kulturkreis' VALUES ('3', 'Westeuropaeischer Kulturkreis', 'Westeuropa', 'Diverse');
INSERT INTO 'kulturkreis' VALUES ('4', 'Osmanischer Kulturkreis', 'Naher Osten, Suedosteuropa', 'Tuerkisch');
INSERT INTO 'kulturkreis' VALUES ('5', 'Mesopotamischer Kulturkreis', 'Naher Osten', 'Akkadisch, Sumerisch');
INSERT INTO 'kulturkreis' VALUES ('6', 'Chinesischer Kulturkreis', 'Ostasien', 'Chinesisch');
INSERT INTO 'kulturkreis' VALUES ('7', 'Nordamerikanischer Kulturkreis', 'Nordamerika', 'Englisch');
INSERT INTO 'kulturkreis' VALUES ('8', 'Indischer Kulturkreis', 'Suedasien', 'Hindi, Sanskrit');
CREATE TABLE 'persoenlichkeit_ereignis' ('persoenlichkeit_ereignis_id' INTEGER PRIMARY KEY, 'persoenlichkeit_id' INTEGER, 'ereignis_id' INTEGER);
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('1', '2', '2');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('2', '3', '13');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('3', '4', '3');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('4', '5', '5');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('5', '7', '6');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('6', '8', '7');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('7', '11', '8');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('8', '11', '9');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('9', '12', '7');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('10', '1', '1');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('11', '18', '19');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('12', '10', '8');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('13', '10', '9');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('14', '9', '8');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('15', '6', '5');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('16', '15', '17');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('17', '16', '5');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('18', '8', '16');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('19', '14', '2');
INSERT INTO 'persoenlichkeit_ereignis' VALUES ('20', '19', '15');
CREATE TABLE 'errungenschaften' ('errungenschaft_id' INTEGER PRIMARY KEY, 'beschreibung' TEXT, 'persoenlichkeit_id' INTEGER);
INSERT INTO 'errungenschaften' VALUES ('1', 'Eroberung Persiens', '2');
INSERT INTO 'errungenschaften' VALUES ('2', 'Roemischer Staatsmann und Feldherr', '3');
INSERT INTO 'errungenschaften' VALUES ('3', 'Begruender des Heiligen Roemischen Reiches', '4');
INSERT INTO 'errungenschaften' VALUES ('4', 'Anfuehrung der Franzosen im Hundertjaehrigen Krieg', '5');
INSERT INTO 'errungenschaften' VALUES ('5', 'Mona Lisa gemalt', '6');
INSERT INTO 'errungenschaften' VALUES ('6', 'Veroeffentlichung der 95 Thesen', '7');
INSERT INTO 'errungenschaften' VALUES ('7', 'Kodifizierung des Code Civil', '8');
INSERT INTO 'errungenschaften' VALUES ('8', 'Entdeckung von Radium und Polonium', '9');
INSERT INTO 'errungenschaften' VALUES ('9', 'Relativitaetstheorie', '10');
INSERT INTO 'errungenschaften' VALUES ('10', 'Fuehrung Grossbritanniens im Zweiten Weltkrieg', '11');
INSERT INTO 'errungenschaften' VALUES ('11', 'Erster Praesident der Vereinigten Staaten', '12');
INSERT INTO 'errungenschaften' VALUES ('12', 'Gruendung des Mongolischen Reiches', '13');
INSERT INTO 'errungenschaften' VALUES ('13', 'Begruender der westlichen Philosophie', '14');
INSERT INTO 'errungenschaften' VALUES ('14', 'Entwicklung der Gravitationstheorie', '15');
INSERT INTO 'errungenschaften' VALUES ('15', 'Entwicklung des Teleskops', '16');
INSERT INTO 'errungenschaften' VALUES ('16', 'Verfassen vieler beruehmter Dramen', '17');
INSERT INTO 'errungenschaften' VALUES ('17', 'Kampf gegen die Apartheid', '18');
INSERT INTO 'errungenschaften' VALUES ('18', 'Begruendung des Konfuzianismus', '19');
INSERT INTO 'errungenschaften' VALUES ('19', 'Eid des Hippokrates', '20');
INSERT INTO 'errungenschaften' VALUES ('20', 'Begruendung der modernen Medizin', '20');
