CREATE DATABASE fortnite;
USE fortnite;
CREATE TABLE spieler (spieler_id INT PRIMARY KEY, benutzername VARCHAR(255), level INT, spielstunden DECIMAL(5,1));
INSERT INTO spieler VALUES ('1', 'Ninja', '350', '2500.5');
INSERT INTO spieler VALUES ('2', 'SypherPK', '280', '1800.0');
INSERT INTO spieler VALUES ('3', 'Tfue', '320', '2100.0');
INSERT INTO spieler VALUES ('4', 'Myth', '290', '1900.5');
INSERT INTO spieler VALUES ('5', 'NickEh30', '310', '2000.0');
INSERT INTO spieler VALUES ('6', 'TimTheTatman', '260', '1700.0');
INSERT INTO spieler VALUES ('7', 'LazarBeam', '240', '1500.0');
INSERT INTO spieler VALUES ('8', 'Loserfruit', '230', '1400.5');
INSERT INTO spieler VALUES ('9', 'DrLupo', '270', '1750.0');
INSERT INTO spieler VALUES ('10', 'NinjaBlevins', '340', '2400.0');
CREATE TABLE spielmodus (modus_id INT PRIMARY KEY, modusname VARCHAR(255), spieleranzahl INT, spieldauer INT);
INSERT INTO spielmodus VALUES ('1', 'Battle Royale Solo', '100', '20');
INSERT INTO spielmodus VALUES ('2', 'Battle Royale Duo', '50', '25');
INSERT INTO spielmodus VALUES ('3', 'Battle Royale Squad', '25', '30');
INSERT INTO spielmodus VALUES ('4', 'Team Rumble', '40', '15');
INSERT INTO spielmodus VALUES ('5', 'Creative', '16', '60');
CREATE TABLE waffen (waffen_id INT PRIMARY KEY, waffenname VARCHAR(255), schaden INT, seltenheit VARCHAR(50));
INSERT INTO waffen VALUES ('1', 'Assault Rifle', '36', 'Episch');
INSERT INTO waffen VALUES ('2', 'Shotgun', '90', 'Legendär');
INSERT INTO waffen VALUES ('3', 'Sniper Rifle', '105', 'Legendär');
INSERT INTO waffen VALUES ('4', 'SMG', '22', 'Selten');
INSERT INTO waffen VALUES ('5', 'Pistol', '28', 'Ungewöhnlich');
INSERT INTO waffen VALUES ('6', 'Rocket Launcher', '110', 'Legendär');
INSERT INTO waffen VALUES ('7', 'Minigun', '18', 'Episch');
INSERT INTO waffen VALUES ('8', 'Grenade Launcher', '100', 'Legendär');
CREATE TABLE kosten (kosten_id INT PRIMARY KEY, itemname VARCHAR(255), v_bucks_preis INT, verfuegbarkeit VARCHAR(50));
INSERT INTO kosten VALUES ('1', 'Battle Pass', '950', 'Saisonal');
INSERT INTO kosten VALUES ('2', 'Skin: Raven', '2000', 'Item Shop');
INSERT INTO kosten VALUES ('3', 'Pickaxe: Reaper', '1500', 'Item Shop');
INSERT INTO kosten VALUES ('4', 'Glider: Dragon', '1200', 'Item Shop');
INSERT INTO kosten VALUES ('5', 'Emote: Floss', '500', 'Item Shop');
INSERT INTO kosten VALUES ('6', 'Bundle: Starter Pack', '800', 'Permanent');
INSERT INTO kosten VALUES ('7', 'V-Bucks Pack: 1000', '1000', 'Permanent');
INSERT INTO kosten VALUES ('8', 'Skin: Skull Trooper', '1500', 'Halloween');
CREATE TABLE spieler_spielmodus (spieler_id INT, modus_id INT);
INSERT INTO spieler_spielmodus VALUES ('1', '1');
INSERT INTO spieler_spielmodus VALUES ('1', '2');
INSERT INTO spieler_spielmodus VALUES ('1', '3');
INSERT INTO spieler_spielmodus VALUES ('2', '1');
INSERT INTO spieler_spielmodus VALUES ('2', '3');
INSERT INTO spieler_spielmodus VALUES ('3', '1');
INSERT INTO spieler_spielmodus VALUES ('3', '2');
INSERT INTO spieler_spielmodus VALUES ('4', '3');
INSERT INTO spieler_spielmodus VALUES ('4', '4');
INSERT INTO spieler_spielmodus VALUES ('5', '1');
INSERT INTO spieler_spielmodus VALUES ('5', '5');
INSERT INTO spieler_spielmodus VALUES ('6', '2');
INSERT INTO spieler_spielmodus VALUES ('6', '3');
INSERT INTO spieler_spielmodus VALUES ('7', '4');
INSERT INTO spieler_spielmodus VALUES ('7', '5');
INSERT INTO spieler_spielmodus VALUES ('8', '1');
INSERT INTO spieler_spielmodus VALUES ('8', '4');
INSERT INTO spieler_spielmodus VALUES ('9', '2');
INSERT INTO spieler_spielmodus VALUES ('9', '3');
INSERT INTO spieler_spielmodus VALUES ('10', '1');
INSERT INTO spieler_spielmodus VALUES ('10', '2');
INSERT INTO spieler_spielmodus VALUES ('10', '3');
CREATE TABLE spieler_waffen (spieler_id INT, waffen_id INT);
INSERT INTO spieler_waffen VALUES ('1', '1');
INSERT INTO spieler_waffen VALUES ('1', '2');
INSERT INTO spieler_waffen VALUES ('1', '3');
INSERT INTO spieler_waffen VALUES ('2', '1');
INSERT INTO spieler_waffen VALUES ('2', '4');
INSERT INTO spieler_waffen VALUES ('3', '2');
INSERT INTO spieler_waffen VALUES ('3', '6');
INSERT INTO spieler_waffen VALUES ('4', '1');
INSERT INTO spieler_waffen VALUES ('4', '5');
INSERT INTO spieler_waffen VALUES ('5', '3');
INSERT INTO spieler_waffen VALUES ('5', '7');
INSERT INTO spieler_waffen VALUES ('6', '2');
INSERT INTO spieler_waffen VALUES ('6', '4');
INSERT INTO spieler_waffen VALUES ('7', '1');
INSERT INTO spieler_waffen VALUES ('7', '8');
INSERT INTO spieler_waffen VALUES ('8', '4');
INSERT INTO spieler_waffen VALUES ('8', '5');
INSERT INTO spieler_waffen VALUES ('9', '2');
INSERT INTO spieler_waffen VALUES ('9', '3');
INSERT INTO spieler_waffen VALUES ('10', '1');
INSERT INTO spieler_waffen VALUES ('10', '6');
INSERT INTO spieler_waffen VALUES ('10', '8');
ALTER TABLE spieler_spielmodus ADD FOREIGN KEY (spieler_id) REFERENCES spieler(spieler_id);
ALTER TABLE spieler_spielmodus ADD FOREIGN KEY (modus_id) REFERENCES spielmodus(modus_id);
ALTER TABLE spieler_waffen ADD FOREIGN KEY (spieler_id) REFERENCES spieler(spieler_id);
ALTER TABLE spieler_waffen ADD FOREIGN KEY (waffen_id) REFERENCES waffen(waffen_id);
