CREATE DATABASE 'schule';
USE 'schule'
CREATE TABLE 'schueler' ('id' INT PRIMARY KEY, 'vorname' VARCHAR(255), 'nachname' VARCHAR(255), 'geburtsdatum' DATE, 'klassen_id' INT);
INSERT INTO 'schueler' VALUES ('1', 'Anna', 'Mueller', '2007-03-15', '1');
INSERT INTO 'schueler' VALUES ('2', 'Max', 'Schmidt', '2006-11-22', '2');
INSERT INTO 'schueler' VALUES ('3', 'Lena', 'Meier', '2007-07-01', '1');
INSERT INTO 'schueler' VALUES ('4', 'Tim', 'Wagner', '2008-01-10', '3');
INSERT INTO 'schueler' VALUES ('5', 'Laura', 'Becker', '2006-05-05', '2');
INSERT INTO 'schueler' VALUES ('6', 'Felix', 'Fischer', '2007-09-19', '1');
INSERT INTO 'schueler' VALUES ('7', 'Mia', 'Weber', '2008-02-28', '3');
INSERT INTO 'schueler' VALUES ('8', 'Ben', 'Schulz', '2006-08-12', '2');
INSERT INTO 'schueler' VALUES ('9', 'Sophie', 'Hoffmann', '2007-04-03', '1');
INSERT INTO 'schueler' VALUES ('10', 'Leon', 'Richter', '2008-10-01', '3');
INSERT INTO 'schueler' VALUES ('11', 'Emilia', 'Klein', '2006-01-20', '2');
INSERT INTO 'schueler' VALUES ('12', 'Jonas', 'Wolf', '2007-06-08', '1');
INSERT INTO 'schueler' VALUES ('13', 'Hannah', 'Neumann', '2008-04-17', '3');
INSERT INTO 'schueler' VALUES ('14', 'Lucas', 'Braun', '2006-09-25', '2');
INSERT INTO 'schueler' VALUES ('15', 'Clara', 'Kaiser', '2007-02-14', '1');
INSERT INTO 'schueler' VALUES ('16', 'Moritz', 'Herzog', '2008-08-07', '3');
INSERT INTO 'schueler' VALUES ('17', 'Lina', 'Vogel', '2006-03-30', '2');
INSERT INTO 'schueler' VALUES ('18', 'Niklas', 'Mayr', '2007-12-05', '1');
INSERT INTO 'schueler' VALUES ('19', 'Julia', 'Kraus', '2008-06-20', '3');
INSERT INTO 'schueler' VALUES ('20', 'Anton', 'Walter', '2006-07-11', '2');
INSERT INTO 'schueler' VALUES ('21', 'Charlotte', 'Huber', '2007-10-28', '1');
INSERT INTO 'schueler' VALUES ('22', 'Paul', 'Ludwig', '2008-05-09', '3');
INSERT INTO 'schueler' VALUES ('23', 'Amelie', 'Frank', '2006-02-01', '2');
INSERT INTO 'schueler' VALUES ('24', 'Oskar', 'Peters', '2007-08-16', '1');
INSERT INTO 'schueler' VALUES ('25', 'Isabel', 'Koehler', '2008-11-29', '3');
INSERT INTO 'schueler' VALUES ('26', 'Finn', 'Bergmann', '2006-04-18', '2');
INSERT INTO 'schueler' VALUES ('27', 'Luisa', 'Seidl', '2007-01-07', '1');
INSERT INTO 'schueler' VALUES ('28', 'Noah', 'Lorenz', '2008-09-14', '3');
INSERT INTO 'schueler' VALUES ('29', 'Maja', 'Baumann', '2006-10-02', '2');
INSERT INTO 'schueler' VALUES ('30', 'Erik', 'Kuehn', '2007-05-23', '1');
CREATE TABLE 'klassen' ('id' INT PRIMARY KEY, 'klassenname' VARCHAR(50), 'kapazitaet' INT, 'jahrgang' INT);
INSERT INTO 'klassen' VALUES ('1', '10A', '30', '10');
INSERT INTO 'klassen' VALUES ('2', '11B', '28', '11');
INSERT INTO 'klassen' VALUES ('3', '9C', '32', '9');
INSERT INTO 'klassen' VALUES ('4', '12A', '25', '12');
INSERT INTO 'klassen' VALUES ('5', '8D', '29', '8');
CREATE TABLE 'lehrer' ('id' INT PRIMARY KEY, 'vorname' VARCHAR(255), 'nachname' VARCHAR(255), 'bueronummer' VARCHAR(10));
INSERT INTO 'lehrer' VALUES ('1', 'Dr. Sabine', 'Schuster', 'B101');
INSERT INTO 'lehrer' VALUES ('2', 'Prof. Thomas', 'Koch', 'B102');
INSERT INTO 'lehrer' VALUES ('3', 'Frau Katrin', 'Lehmann', 'B103');
INSERT INTO 'lehrer' VALUES ('4', 'Herr Martin', 'Schneider', 'B104');
INSERT INTO 'lehrer' VALUES ('5', 'Dr. Julia', 'Hartmann', 'B105');
INSERT INTO 'lehrer' VALUES ('6', 'Frau Petra', 'Stein', 'B106');
INSERT INTO 'lehrer' VALUES ('7', 'Herr Daniel', 'Jung', 'B107');
INSERT INTO 'lehrer' VALUES ('8', 'Frau Andrea', 'Winter', 'B108');
INSERT INTO 'lehrer' VALUES ('9', 'Herr Robert', 'Sommer', 'B109');
INSERT INTO 'lehrer' VALUES ('10', 'Frau Elke', 'Gross', 'B110');
CREATE TABLE 'faecher' ('id' INT PRIMARY KEY, 'fachbezeichnung' VARCHAR(255), 'wochenstunden' INT, 'leistungspunkte' INT);
INSERT INTO 'faecher' VALUES ('1', 'Mathematik', '4', '5');
INSERT INTO 'faecher' VALUES ('2', 'Deutsch', '4', '5');
INSERT INTO 'faecher' VALUES ('3', 'Englisch', '3', '4');
INSERT INTO 'faecher' VALUES ('4', 'Physik', '3', '4');
INSERT INTO 'faecher' VALUES ('5', 'Chemie', '2', '3');
INSERT INTO 'faecher' VALUES ('6', 'Biologie', '2', '3');
INSERT INTO 'faecher' VALUES ('7', 'Geschichte', '2', '3');
INSERT INTO 'faecher' VALUES ('8', 'Geographie', '2', '3');
INSERT INTO 'faecher' VALUES ('9', 'Sport', '2', '2');
INSERT INTO 'faecher' VALUES ('10', 'Kunst', '1', '2');
INSERT INTO 'faecher' VALUES ('11', 'Musik', '1', '2');
INSERT INTO 'faecher' VALUES ('12', 'Informatik', '2', '3');
CREATE TABLE 'lehrer_faecher' ('lehrer_id' INT, 'faecher_id' INT);
INSERT INTO 'lehrer_faecher' VALUES ('1', '1');
INSERT INTO 'lehrer_faecher' VALUES ('1', '4');
INSERT INTO 'lehrer_faecher' VALUES ('2', '2');
INSERT INTO 'lehrer_faecher' VALUES ('2', '7');
INSERT INTO 'lehrer_faecher' VALUES ('3', '3');
INSERT INTO 'lehrer_faecher' VALUES ('3', '11');
INSERT INTO 'lehrer_faecher' VALUES ('4', '1');
INSERT INTO 'lehrer_faecher' VALUES ('4', '12');
INSERT INTO 'lehrer_faecher' VALUES ('5', '5');
INSERT INTO 'lehrer_faecher' VALUES ('5', '6');
INSERT INTO 'lehrer_faecher' VALUES ('6', '2');
INSERT INTO 'lehrer_faecher' VALUES ('6', '10');
INSERT INTO 'lehrer_faecher' VALUES ('7', '3');
INSERT INTO 'lehrer_faecher' VALUES ('7', '8');
INSERT INTO 'lehrer_faecher' VALUES ('8', '9');
INSERT INTO 'lehrer_faecher' VALUES ('8', '5');
INSERT INTO 'lehrer_faecher' VALUES ('9', '4');
INSERT INTO 'lehrer_faecher' VALUES ('9', '1');
INSERT INTO 'lehrer_faecher' VALUES ('10', '6');
INSERT INTO 'lehrer_faecher' VALUES ('10', '2');
CREATE TABLE 'klassen_faecher' ('klassen_id' INT, 'faecher_id' INT);
INSERT INTO 'klassen_faecher' VALUES ('1', '1');
INSERT INTO 'klassen_faecher' VALUES ('1', '2');
INSERT INTO 'klassen_faecher' VALUES ('1', '3');
INSERT INTO 'klassen_faecher' VALUES ('1', '4');
INSERT INTO 'klassen_faecher' VALUES ('1', '7');
INSERT INTO 'klassen_faecher' VALUES ('1', '9');
INSERT INTO 'klassen_faecher' VALUES ('2', '1');
INSERT INTO 'klassen_faecher' VALUES ('2', '2');
INSERT INTO 'klassen_faecher' VALUES ('2', '3');
INSERT INTO 'klassen_faecher' VALUES ('2', '5');
INSERT INTO 'klassen_faecher' VALUES ('2', '6');
INSERT INTO 'klassen_faecher' VALUES ('2', '12');
INSERT INTO 'klassen_faecher' VALUES ('3', '1');
INSERT INTO 'klassen_faecher' VALUES ('3', '2');
INSERT INTO 'klassen_faecher' VALUES ('3', '3');
INSERT INTO 'klassen_faecher' VALUES ('3', '8');
INSERT INTO 'klassen_faecher' VALUES ('3', '10');
INSERT INTO 'klassen_faecher' VALUES ('3', '11');
INSERT INTO 'klassen_faecher' VALUES ('4', '1');
INSERT INTO 'klassen_faecher' VALUES ('4', '2');
INSERT INTO 'klassen_faecher' VALUES ('4', '3');
INSERT INTO 'klassen_faecher' VALUES ('4', '4');
INSERT INTO 'klassen_faecher' VALUES ('4', '5');
INSERT INTO 'klassen_faecher' VALUES ('4', '6');
INSERT INTO 'klassen_faecher' VALUES ('5', '1');
INSERT INTO 'klassen_faecher' VALUES ('5', '2');
INSERT INTO 'klassen_faecher' VALUES ('5', '3');
INSERT INTO 'klassen_faecher' VALUES ('5', '7');
INSERT INTO 'klassen_faecher' VALUES ('5', '8');
INSERT INTO 'klassen_faecher' VALUES ('5', '9');
